name: appetizer
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.1+24

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^7.4.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_analytics: ^10.4.4
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  firebase_remote_config: ^4.2.4
  flutter_screenutil: ^5.7.0
  get: ^4.6.5
  package_info_plus: ^5.0.1
  get_it: ^7.6.0
  intl: ^0.18.0
  path_provider: ^2.0.15
  bloc: ^8.1.2
  fluttertoast: ^8.2.2
  fswitch_nullsafety: ^2.0.2
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  month_picker_dialog: ^2.0.2
  hive: ^2.2.3
  device_preview: ^1.1.0
  retrofit: ^4.0.1
  dio: ^5.3.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  sentry_flutter: ^7.9.0
  sentry_dio: ^7.9.0
  flutter_svg_provider: ^1.0.6
  url_launcher: ^6.1.12
  flutter_inappwebview: ^6.0.0
  flutter_native_splash: ^2.3.2
  mixpanel_flutter: ^2.2.0

dev_dependencies:
  auto_route_generator: ^7.1.2
  build_runner: ">2.3.0 <4.0.0"
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  retrofit_generator: ^8.0.6
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_icons:
  image_path_android: "assets/icons/logo_rounded.png"
  image_path_ios: "assets/icons/logo_squared.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFCB74"
  image: "assets/images/icons/splash_icon.png"
  fullscreen: true

  android_12:
    color: "#FFCB74"
    image: "assets/icons/logo_outlined.png"


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/meal_card/
    - assets/images/icons/
    - assets/icons/
    - assets/icons/bottom_navigator/
    - shorebird.yaml
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
